name: image-retention

on:
  schedule:
    - cron: '17 2 * * *' # daily
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

env:
  ORG: swarmnative
  PACKAGE: swarm-s3-mounter
  RETENTION_DAYS: '30'
  FP_RETENTION_DAYS: '14'
  UNTAGGED_DAYS: '7'
  KEEP_TAG_RE: '^v\d+\.\d+\.\d+$|^latest$|^main$|^nightly$|^stable$'
  DRY_RUN: 'false' # set 'true' to preview without deleting

jobs:
  prune-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Show policy
        run: |
          echo "Org: $ORG, Package: $PACKAGE"
          echo "Keep regex: $KEEP_TAG_RE"
          echo "Retention: $RETENTION_DAYS d, fp: $FP_RETENTION_DAYS d, untagged: $UNTAGGED_DAYS d"
          echo "Dry run: $DRY_RUN"

      - name: Prune GHCR container versions
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          set -euo pipefail

          api_list() {
            local page=$1
            gh api -H "Accept: application/vnd.github+json" \
              "/orgs/${ORG}/packages/container/${PACKAGE}/versions?per_page=100&page=${page}"
          }

          now=$(date -u +%s)
          deleted=0
          page=1
          while :; do
            data=$(api_list "$page")
            count=$(jq 'length' <<<"$data")
            [[ "$count" == "0" ]] && break

            while IFS=$'\t' read -r id updated tags; do
              # age in days
              ts=$(date -u -d "$updated" +%s || date -u -jf "%Y-%m-%dT%H:%M:%SZ" "$updated" +%s)
              age=$(( (now - ts) / 86400 ))

              IFS=',' read -r -a arr <<<"${tags}"
              protected=false
              has_fp=false
              has_tag=false
              for t in "${arr[@]}"; do
                [[ -n "${t}" ]] && has_tag=true || true
                if [[ "$t" =~ $KEEP_TAG_RE ]]; then protected=true; fi
                if [[ "$t" =~ ^fp- ]]; then has_fp=true; fi
              done

              # Decide ttl
              ttl=$RETENTION_DAYS
              if [[ "$has_fp" == true ]]; then ttl=$FP_RETENTION_DAYS; fi
              if [[ "$has_tag" == false ]]; then ttl=$UNTAGGED_DAYS; fi

              if [[ "$protected" == true ]] || [[ "$age" -lt "$ttl" ]]; then
                continue
              fi

              echo "Deleting version id=$id age=${age}d tags=[${tags}] ttl=${ttl}d"
              if [[ "$DRY_RUN" != "true" ]]; then
                gh api -X DELETE \
                  -H "Accept: application/vnd.github+json" \
                  "/orgs/${ORG}/packages/container/${PACKAGE}/versions/${id}" || true
              fi
              deleted=$((deleted+1))
            done < <(jq -r '.[] | [.id, .updated_at, (.metadata.container.tags | join(","))] | @tsv' <<<"$data")

            page=$((page+1))
          done

          echo "Deleted versions: $deleted"

  prune-dockerhub:
    if: ${{ secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != '' }}
    runs-on: ubuntu-latest
    env:
      DH_NAMESPACE: swarmnative
      DH_REPO: swarm-s3-mounter
    steps:
      - name: Show policy (Docker Hub)
        run: |
          echo "Docker Hub: ${DH_NAMESPACE}/${DH_REPO}"
          echo "Keep regex: $KEEP_TAG_RE"
          echo "Retention: $RETENTION_DAYS d, fp: $FP_RETENTION_DAYS d"
          echo "Dry run: $DRY_RUN"

      - name: Prune Docker Hub tags
        shell: bash
        env:
          DH_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DH_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          set -euo pipefail
          apt-get update >/dev/null 2>&1 || true
          apt-get install -y jq >/dev/null 2>&1 || true

          jwt=$(curl -fsSL -H 'Content-Type: application/json' \
            -d "{\"username\":\"${DH_USER}\",\"password\":\"${DH_TOKEN}\"}" \
            https://hub.docker.com/v2/users/login/ | jq -r .token)
          if [[ -z "$jwt" || "$jwt" == "null" ]]; then
            echo "Docker Hub login failed" >&2; exit 1;
          fi

          now=$(date -u +%s)
          deleted=0
          page=1
          while :; do
            url="https://hub.docker.com/v2/repositories/${DH_NAMESPACE}/${DH_REPO}/tags/?page_size=100&page=${page}"
            data=$(curl -fsSL -H "Authorization: JWT ${jwt}" "$url") || break
            count=$(jq '.results | length' <<<"$data")
            [[ "$count" == "0" ]] && break

            while IFS=$'\t' read -r name updated; do
              # protect by regex
              if [[ "$name" =~ $KEEP_TAG_RE ]]; then continue; fi

              ts=$(date -u -d "$updated" +%s || date -u -jf "%Y-%m-%dT%H:%M:%SZ" "$updated" +%s)
              age=$(( (now - ts) / 86400 ))
              ttl=$RETENTION_DAYS
              if [[ "$name" =~ ^fp- ]]; then ttl=$FP_RETENTION_DAYS; fi

              if [[ "$age" -lt "$ttl" ]]; then continue; fi

              echo "Deleting Docker Hub tag: ${name} (age=${age}d ttl=${ttl}d)"
              if [[ "$DRY_RUN" != "true" ]]; then
                curl -fsSL -X DELETE -H "Authorization: JWT ${jwt}" \
                  "https://hub.docker.com/v2/repositories/${DH_NAMESPACE}/${DH_REPO}/tags/${name}/" >/dev/null || true
              fi
              deleted=$((deleted+1))
            done < <(jq -r '.results[] | [.name, .last_updated] | @tsv' <<<"$data")

            page=$((page+1))
          done

          echo "Deleted Docker Hub tags: $deleted"

